version: '2'

services:
  nodejs:
    build: ./docker/node
    links:
      - mysql:mysql
    ports:
      - 3000:3000
      - 4000:4000
      - 8081:8080
    volumes:
      - .:/var/www/app
    networks:
      app:
        ipv4_address: "10.6.0.2"

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=r00tf0rmy5ql
    - MYSQL_DATABASE=boilerplate
    - MYSQL_USER=developer
    - MYSQL_PASSWORD=d3v3l0p3r
    ports:
    - 3307:3306
    volumes:
    - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      app:
        ipv4_address: "10.6.0.3"

networks:
  app:
    driver: bridge
    ipam:
      config:
      - subnet: "10.6.0.0/16"
        gateway: "10.6.0.1"
